apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  labels:
    app.kubernetes.io/name: {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image }}
