apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  labels:
    app.kubernetes.io/name: {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
          - name: DISCORD_TOKEN
            value: {{ .Values.envar.DISCORD_TOKEN }}
          - name: DISCORD_GUILD
            value: {{ .Values.envar.DISCORD_GUILD }}
          - name: DEBUG
            value: {{ .Values.envar.DEBUG }}
