name: push image to docker hub

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  PROJECT_NAME: chatbot
  TAG: latest

jobs:
  build_image:
    name: building image for registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t python-docker .

      - name: Log in to docker hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.DOCKERHUB_KEY }}

      - name: tag image
        run: docker tag python-docker erikhalt/${{ env.PROJECT_NAME }}:${{ env.TAG }}

      - name: push image to dockerhub
        run: docker push erikhalt/${{ env.PROJECT_NAME }}:${{ env.TAG }}